# Generated by Django 5.2.15 on 2026-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9800000000, max_length=15),
            preserve_default=False,
        ),
    ]
